:git: https://github.com/iacgame/aws_playbooks.git

= IaCStart - So it Begins

By now you should have gotten an introduction to what Infrastructure-as-Code is all about, what you can expect in your game and what core technologies you'll use. Before you will dive into building infrastructures here is a short introduction what you'll do next:

* The first step is to get access to the tools you'll use: Github, Ansible Tower, and the AWS console.
* To get you started you'll get some simple tasks with a lot of help from this guide and the facilitators.
* Afterwards you'll get game modules with tasks that 
** will get increasingly more complex
** come with less help

== Let's get started

Without further ado let's simply get started, you'll get more instructions on your way.

TIP: Remember to have fun!


== Source Code Management with GitHub

IaC is built on, well, the code that describes your Infrastructure. This content has to live somewhere. So the first step is to create a Github account for your team and to add content that was already prepared for you.


=== Create your GitHub team account and clone the repository

* Open https://github.com
* Log-in with your existing GitHub account or create a new one
* Fork the Playbooks into your Account. To do so:
** Open {git}
** Click on "Fork" in the upper right corner of the website and choose your Account as target

=== Automation System with Ansible Tower

As you've learned already Ansible Tower is an execution environment for running Ansible automation in Enterprise IT environments. 
To get access to Tower's web interface you just have to fire up a browser. The URL, Username, and password will be provided separately per Team by the facilitators. 

By now your Tower is pretty empty, have a look around anyway.

== Task 1: Configure Ansible Tower for AWS

=== Create Cloud Access Credentials

The first step is to configure Ansible Tower to talk to AWS using your account credentials. This is straight forward, you have to use the AWS access key, which you've downloaded during the AWS user setup and configure it in Tower as a cloud credential. 
To do so work through these steps:

* Bring up the Tower web interface and configure a new cloud credential:
** Select "Credentials" in the left menu
** Add a new Cloud Credential by clicking the "+" button
** Fill in the *NAME* field with *AWS* 
** In the *CREDENTIAL TYPE* Field, click the magnifying glass and select *Amazon Web Services* as type
** Now the fields *ACCESS KEY* and *SECRET KEY* open, enter the respective keys. The keys can be found in the downloaded CSV file from AWS. 
** Save the credentials

=== SSH Credentials

In the next steps, you need to add the ssh private key to the Ansible Tower, so that you can use this key during the playbooks.

* Bring up the Tower web interface and configure a new cloud credential:
** Select "Credentials" in the left menu
** Add a new Cloud Credential by clicking the "+" button
** Fill in the *NAME* field with *AWS SSH* 
** In the *CREDENTIAL TYPE* Field, click the magnifying glass and select *Machine* as type
** Open the *ssh-access.pem* file, which you have downloaded during module 0, with a text editor and copy the whole content.
** Paste the content into the *SSH PRIVATE KEY* field. 
** Save the credentials

=== Add the Github Repository as Tower Project

With the credentials in place, you'll run a first simple job to see if everything works as expected. During the preparation steps, you cloned a GitHub repository with a lot of Ansible content to your GitHub account.

TIP: Ansible content is mainly the Playbooks, which are the "recipes" which describe what steps should be automated in your IT environment. Besides Ansible automation content can be variable files, files, file templates and more. But one step after the other.

So to check everything works and to walk you through the process of setting up and running Ansible automation against AWS do the following in the Tower web UI:

* Create a new *Project*. Projects in Tower are pointers to version control systems holding the needed files, in this case, your Github repository.

** Bring up the Tower web interface
** Select "Projects" in the left menu
** Add a new Project by clicking the "+" button
*** Project Name "IaC Start"
*** SCM Type "Git"
*** SCM URL (Your Repository, the URL can be copied by opening the repository on GitHub, click the "Clone or download" button and then the clipboard icon)

WARNING: Make sure to use the *https* URL

** Save the project

=== First Test: Create a Job Template

* Now create a *Job Template*. Tower Job Templates describe an Ansible job (like a blueprint) which can later be used to start a job.

** Bring up the Tower web interface
** Select "Templates" in the left menu
** Add a new Job Template by clicking the "+" button and select "Job Template"
*** Name "Elastic IP"
*** Job Type "Run"
*** Inventory "Demo Inventory"
*** Project "IaC Start"
*** Playbook "allocate_eip.yml"
*** Credentials "AWS" (Type: "Amazon Web Services" )


So now you have configured Tower to run one of the Playbooks from your Github repo. Before starting it, have a look at the Playbook to get an idea of how it looks like and to get an idea of what it might do.

TIP: Ansible Playbooks always contain some headers with specifics about how to run it and then, most importantly, a list of one or more tasks. Ansible tasks use so-called modules to do the dirty work together with some parameters to specify the job.

Here is your Playbook:

----
---
- hosts: localhost
 connection: local
 gather_facts: False

 tasks:
 - name: allocate a new elastic IP without associating it to anything
 ec2_eip:
 state: present
 region: eu-central-1
 register: eip
----

It doesn't look too complicated, what do you think? All it does is to create an *EC2 Elastic IP* in your account which can be attached to instances (virtual machines) later.

=== Start the First Ansible Job

It's time now to see everything come together. In the *Job Template* view in Tower click the "Rocket" icon to run a job from the template. Have a good look at the output, in the end, it should say:

----
PLAY RECAP ******************************************** 

localhost : ok=1 changed=1 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0 
----

An error would stick out to you in red, but it should be fine for now. You have created an *AWS EIP* using some textfiles in a Github repository! 

For the fun of it go to your AWS web console to make sure the EIP is there!

* Open the AWS console https://console.aws.amazon.com/
* Log-in with the provided Credentials
* Open the EC2 Console within the service menu
* Verify that you are connected to the *Europa (Frankfurt)eu-central-1* Region in the top right corner. If not, change to that region.
* Click on the "Elastic IPs" in the middle of the screen
* Write down the Public IPv4 address, which was created by the playbook before.

WARNING: Communicate the IP address together with the team name to the facilitators. aka. *MR. DNS*

== Review what you have done so far.

* You have log-in into the AWS console and created a user to work with. 
* You have created the *access key* to access the AWS API and an *ssh key pair* to login into the servers on AWS.
* You have login into the Red Hat Ansible Tower system, which will be the central system to manage and execute every automation step.
* You have stored the *access key* and *ssh key pair* within the secret store of the Ansible Tower so that the Ansible Tower can use these credentials.
* You have created your first Ansible Automation Workflow to execute an existing playbook, which will log in to AWS with your key and created an *Elastic IP* as a fixed IP for your Website.

These steps will be the foundation for the rest of the day. You will now use Ansible Tower to point to the playbook, which you will create to deploy all parts of your environment and to fix any broken part, where maybe the Chaos Monkey or his little helpers will give you some trouble.





