= IaCStart - Initial Deployment

By now you should have access to your 

* AWS account and web console
* Github account
* Ansible Tower web interface

And the following tasks should have been completed:

* AWS user and access key/SSH key have been created
* Github repos with IaC Playbooks and application code have been cloned into your team account
* Ansible Tower is configured with your AWS credentials and Github repositories

WARNING: If not please don't proceed and ask for assistance!

== Using Ansible Tower Workflows

Workflows are a feature that Tower adds to Ansible Automation. You basically link separate Playbooks (which could have been authored by different people) into one "Meta-Playbook".

We'll use Workflows in our scenario, just remember they are part of Tower's feature set and are not part of Ansible Engine/command line. So let's get started, you have a repository filled with Playbooks you need to integrate using Tower.

== Create an empty Tower Workflow

As a starting point create the Workflow without running any Playbooks, we'll add them one by one later on.

* Open your Ansible Tower web interface.
* In the menu bar to the left choose *Resources -> Templates*.
* In the upper right click the green *+* icon and choose *Workflow Template*.
* Enter a name for the Workflow: *iacstart* and click the *SAVE* button.

The visual workflow designer opens, hit the *CLOSE* button it for now. Now let's add the first Playbook to have Ansible actually do something. To use an Ansible Playbook as part of a workflow you have to:

* Create a Job Template using a Playbook.
* Add the Job Template to the Workflow Template.

== Create an AWS *Virtual Private Cloud* (VPC)

As already discussed during the introduction the first resource you need in AWS (and other clouds) is a VPC to separate your infrastructure components from other stuff probably running in your cloud environment.

The Playbook named `create_vpc_complete.yml` already exists in your Github repository. First create a Job Template to make it usable in Tower:

=== Create Job Template

* In *Resources -> Templates* click the green *+* and choose *Job Template*. Fill in the needed fields:

* Name it
** *Name*: *iac_create_vpc*
* What hosts to run on 
** *Inventory*: localhost
* The Github repo
** *Project*: iacstart
* Choose the Playbook from the repo
** *Playbook*: create_vpc_complete.yml
* What credentials to use
** *Credentials*: AWS
* And finally click *SAVE*

WARNING: While you get more familiar with Ansible Tower we'll use less and less verbose instructions in this guide.

=== Add Template to Workflow

Now add the Job Template to your Workflow using the Workflow Visualizer:

* In Tower's web interface open your Workflow Template by going to *Resources -> Templates* and then clicking your workflow template name.
* Click the *WORKFLOW VISUALIZER* button
* You get an empty workflow window. 

Add the first Node by clicking *START*, an empty node gets added, configure it in the frame to the right: 

* Leave the node type as *Template*
* Search and select the *iac_create_vpc* job template
* Click the *SELECT* button
* Click *SAVE*

[TIP] 
.What have you done so far? 
====
You have:

* Created an empty Workflow
* Created a Job Template to run a Playbook
* Added the template as the first step/node in your workflow
====

=== Parameterize and Run the Workflow

You could now run the Workflow (it would of course only execute the first Playbook) but something is missing: Have a look at the `create_vpc_complete.yml` Playbook in Github. In the Ansible-code are a good number of *{{ ... }}* constructs. These are variables which have to be filled with content, making the Playbook more versatile without always having ti change the code itself.

There are multiple ways to supply variable content to a Playbook/Job Template, in out case put it into the Workflow definition in Tower:

* Open the Workflow configuration in Tower
* Find the text field *EXTRA VARIABLES*
* Add the following variable definitions:

----
---
vpc: "iacstart"
vpc_cidr: "10.0.0.0/16"
subnet_cidr: "10.0.1.0/24"
state: "present"
region: "us-east-1"
----

WARING: Make sure to keep the *---* in place as they are! This tells Tower the format is YAML.

* Click *SAVE*

*You are ready to run the workflow*

* Go to *Resources -> Templates* and click the "Rocket" icon for your workflow to launch it.
* Watch it run, you can get detailed information by clicking the *DETAILS* button of the workflow node.

Your Workflow should have created a new VPC, check in the AWS console. Now try to run the workflow again. As your IaC automation is idempotent it describes of how "things should be" regardless how many times you run it.

=== Create AWS Instances in your VPC

The initial version of your application will consist of one webserver and one database server. The next step in your Infrastructure-as-Code setup is to deploy two cloud instances (Virtual Machines) to run your application. In the cloud you usually don't install operating systems from scratch, AWS (and other cloud providers) come with a large number of pre-made images you can use to start your instances. In AWS these are called "Amazon Machine Images (AMI)".

A Playbook to deploy instances in AWS already exists in your Github repo, but you need some information to pass as parameters:

* The *Instance Type*, defining the sizing of the VM (Memory, CPUs etc)
* An *AMI ID*, basically what image/operating system to use.
* What *SSH Key* to inject into the instance, so Ansible can later on connect to it using SSH. You already created this key during the AWS setup steps.

==== Find the Instance Size

WARNING: Before doing anything in the AWS web console, make sure you are in Region *US East (N. Virginia)*, check the drop-down in the upper right.

First find a fitting instance size: Your VM should have *2 vCPUs and 2048 MiB Memory*.

WARNING: Using another size will result in points reduction (not to mention AWS costs... ;-)

In your AWS web console open *Services -> EC2*. In the left menu bar choose *Instance Types*. You will get a list of all available instance sizes for this region, use the filter to find the one providing the neede resources, but not more. There should only be two instance types which combine the right vCPU count and Memory size. 

Take note of the instance type.

==== Find the Amazon Machine Image (AMI) ID 

There are multiple ways to find an AMI suitable for your application. In our scenario you are going to  use *CentOS 7* in the latest release as operating system. So you have to:

* Find the proper AMI ID to pass to the Playbook
* Make sure the AMI was created from a reliable source

Finding the proper AMI ID can be tricky, here take this road:

* Go to *www.centos.org -> Get CentOS now -> Amazon Web Services*
* This will take you to the AWS Marketplace
* On the overview page click *CentOS 7 (x86_64) - with Updates HVM*
* You'll now get lots of information about the image, click the *Continue to Subscribe* button to the upper right.
* Now click the *Continue to Configuration* button (bear with me, nearly there...)
* AMI IDs are region-specific, on the next page choose *US East (N. Virginia)* as *Region* and, lo and behold, you'll get the AMI ID to the right.
* Copy the ID

NOTE: Even if this feels tiresome for now, remember you would have to go through these steps only once, after your automation is finished you can just execute it again and again.

=== Extend the Workflow 

Now your are ready to extend your workflow by adding the Playbook for creating instances. You have done the required steps already when integrating the VPC creation into the workflow. Here is what you have to do:

* Create a Job Template named *iac_create_instance* pointing to the `create_instance.yml` Playbook.
* Define the variables needed by the Playbook:
** Instance Type 
** AMI ID you found for the CentOS AMI
** The name of your SSH key
* by adding the following to the *EXTRA VARIABLES*:

----
instance_type: <instance type>
ami_id: "<AMI ID>>"
ssh_key: "<SSH Key>"
----

* Extend your workflow using the *WORKFLOW VISUALIZER* to add a new node after the node creating the VPC. Configure the node to run the *iac_create_instance* Job Template.

*Go and execute the Workflow Template!*
















