:nfs-share: 10.10.10.4:/elated-fervent-engelbart

= IaCStart - Scale the frontend to cope with the load

The marking department has changed the process to ship new images for the web site. At the moment the images are part of the application deployment, which means, that every image change involves an application deployment. 

The images will be provided on a central NFS Storage, which will utilize the Cloud Volume Services from NetApp on AWS.

The CVS is available from the central AWS team. Due to the architecture of this game environment, you need to utilize a other VPC and Subnet, which we have already deployed to your account. 

So you need to destroy your current environment and redeploy the whole infrastructure into the given Subnet. You can identify the target Subnet in the VPC console with the CIDR, which starts with 10.128.


The NFS share name is {nfs-share}

To use the new images you need to mount the NFS share and you need to deploy the new version of the application.

Only the revenue of the new application version will count against your overall result. 
