:icons: font

= IaCStart - Initial Web Shop Deployment

== Introduction

As this is a short version of the IACStart game most infrastructure components and configurations have been prepared in advance. 

* Ansible Tower will be the *central automation platform* where all the automation tasks are stored and executed. An Ansible Tower instance has been installed for each team. 
* Ansible Tower has already been pre-configured with most objects you need to deploy AWS infrastructure:
** *Cloud Credentials* to allow Tower to connect to AWS
** *Credentials* (SSH keys) to login to AWS instances (Virtual Machines) you have deployed
** A *Project* that points to a Github repository with the required Ansible Playbooks
** *Job Templates* which run the Ansible Playbooks (the automation recipes) 
** A *Dynamic Inventory* to get access information for instances deployed to AWS

=== Using Ansible Tower Workflows

Your main task will be to create an Ansible Tower Workflow. Workflows are a feature that Tower adds to Ansible Automation. You basically link separate Job Templates (Playbooks) (which could have been authored by different people) into one "Meta-Playbook".

We'll use a Workflow in our scenario, just remember they are part of Tower's feature set and are not part of Ansible Engine/command line. So let's get started, your Tower has been prepared with all needed configuration objects in advance, you only need to create the Workflow itself!

== Create an empty Tower Workflow

As a starting point create the Workflow without any Job Templates, we'll add them one by one later on.

* Open your Ansible Tower web interface.
* In the menu bar to the left choose *Templates*.
* In the upper right click the green *+* icon and choose *Workflow Template*.
* Enter a name for the Workflow: *iacstart* and click the *SAVE* button.

The visual workflow designer opens, hit the *CLOSE* button it for now. Your Workflow is now ready to be filled with Job Templates (that run Playbooks). 

TIP: *Workflow Templates* are listed together with normal *Job Templates* under *Templates* in Ansible Tower. But they are clearly marked as *Workflow Templates*!

== Add Job Templates to the Workflow

The following tasks will let you add (already existing) Job Templates to the Workflow. 

=== Create an AWS *Virtual Private Cloud* (VPC)

As already discussed during the introduction the first resource you need in AWS (and other clouds) is a VPC to separate your infrastructure components from other stuff probably running in your cloud environment. So let's start by automating the creation of the VPC.

The Job Template *iac_create_vpc* will do this for you when provided with the proper parameters. 

==== Add Job Template to Workflow

Add the Job Template to the Workflow you created above using the Workflow Visualizer:

* In Tower's web interface open your Workflow Template by going to *Templates* and then clicking your *iacstart* workflow template.

* Click the *WORKFLOW VISUALIZER* button
* You get your empty Workflow window. 

TIP: In an Ansible Tower workflow *steps* are represented by *Nodes* (represented as rectangles)

Add the first Node by clicking *START*, an empty node gets added, configure it in the frame to the right: 

* Leave the node type as *Template*
* Search and select the *iac_create_vpc* job template
* Click the *SELECT* button
* Click *SAVE*

[TIP] 
.What have you done so far? 
====
You have:

* Created an empty Workflow
* Added an existing Job Template as the first node (step) to your workflow
====

=== Parameterize and Run the Workflow

You could now run the Workflow (it would of course only execute the first Playbook) but something is missing. Ansible uses variables to make Playbooks more versatile without always having to change the Ansible code itself. Job Templates represent Playbooks in Ansible Tower.

There are multiple ways to supply variable content to a Job Template, in this case put it into the Workflow definition:

* In Ansible Tower go to *Templates* and open the Workflow *iacstart*
* Find the text field *EXTRA VARIABLES*
* Add the following variable definitions:

----
---
vpc: "iacstart"
vpc_cidr: "10.101.0.0/16"
subnet_cidr: "10.101.1.0/24"
state: "present"
region: "us-east-1"
aws_zone: "us-east-1a"
----

WARNING: Make sure to keep the *---* in place as they are! This tells Tower the format is YAML.

* Click *SAVE*

*You are ready to run the workflow*

* Go to *Templates* and click the "Rocket" icon for your *iacstart* workflow to launch it.
* Watch it run, you can get detailed information by clicking the *DETAILS* button of the workflow node. The easiest way back to the Workflow output is the browsers back button.

Your Workflow should have created a new VPC, check in the AWS console by switching to the *VPC* service. Now try to run the workflow again. As your IaC automation is *idempotent* it describes of how "things should be" regardless of how many times you run it.

TIP: *Idempotence* is the property of certain operations in mathematics and computer science whereby they can be applied multiple times without changing the result beyond the initial application. (Wikipedia)

=== Create AWS Instances in your VPC

The initial version of your application will consist of one webserver and one database server. The next step in your Infrastructure-as-Code setup is to deploy two cloud instances (Virtual Machines) to run your application. In the cloud you usually don't install operating systems from scratch, AWS (and other cloud providers) come with a large number of pre-made images you can use to start your instances. In AWS these are called "Amazon Machine Images (AMI)".

A Job Template to deploy instances in AWS already exists in your Tower, but again you need some information to pass as parameters:

* The *Instance Type*, defining the sizing of the VM (Memory, CPUs etc)
* An *AMI ID*, basically what image/operating system to use.
* What *SSH Key* to inject into the instance, so Ansible can later connect to it using SSH. The key has already been created as *sshkey* in AWS.

=== Extend the Workflow 

Now you are ready to extend your workflow by adding the Job Template for creating instances. You have done the required steps already when integrating the VPC creation into the workflow. Here is what you have to do:

* In Tower open *Templates->iacstart* and then the *WORKFLOW VISUALIZER*
* Now extend your workflow using the *WORKFLOW VISUALIZER* to add a new node:
**  Hover the mouse pointer over the existing node and click the green *+* icon after the node which creates the VPC. 
** Configure the node to run the *iac_create_instance* Job Template.
** Click *SELECT* then *SAVE*

Before running the *Workflow* you need to define some more variables needed by the Playbook. *Add* them to the *EXTRA VARIABLES* field of the *iacstart* Workflow by copy/pasting the following variables under the already existing ones:

----
instance_type: "t3.small"
ami_id: "ami-0d03e44a2333dea65"
ssh_key: "sshkey"
----

*Go and execute the Workflow Template* by clicking the Rocket item in the Template list in Ansible Tower.

=== Check the State of your Nation

If you go to the AWS web console now (set to the correct region) you should see two new instances coming up in the EC2 Service dashboard. When the icons in the *Instance State* and *Status Checks* columns change to green your instances are happily up and running. 

[TIP] 
.What have you done so far? 
====
You have:

* Created an empty Workflow
* Added an existing Job Template to create a VPC
* Added another Job Template to deploy your instances
====

=== Installing the Application

But just having two VMs running is not providing lots of business value. So you'll have do add Job Templates for application installation and configuration to the workflow.

WARNING: *But Wait*: Before we can go from deploying instances to installing something inside of them, we have to get the IP addresses and make them known to Ansible Tower so Ansible can talk to them.

==== Adding the Inventory Sync to the Workflow

The Inventory sync has already been created for you. You just have to add it to the workflow following the instance deploy step. But at first make sure it works:

* In Tower open *Inventories -> iacstart*
* Click the *HOSTS* button, there shouldn't be any hosts listed yet
* Run the Inventory sync by clicking the *SOURCES* button and then the circular arrow (start sync) to the right of the *iacstartaws* source.
* If you now check back after the sync has finished with the *HOSTS* button you should see your two hosts listed with their IP addresses.

Now add the Inventory sync to the Workflow:

* Open the Workflow by clicking the name from the template list
* Open the *WORKFLOW VISUALIZER*
* Click the green *+* icon on the *iac_create_instance* node to open a new node
* Configure the node to be an *Inventory Sync* node
* Choose the inventory source to use
* Click *SELECT* and *SAVE*

[TIP] 
.What have you done so far? 
====
You have:

* Created an empty Workflow
* Added an existing Job Template to create a VPC
* Added another Job Template to deploy your instances
* Added a step to make new instances known to Ansible for further tasks
====

==== Add the Application Deployment Jobs 

Your Ansible Tower contains two Job Templates that deploy a simple two-tier (webserver and database) application to your instances: 

* *iacstart_install_database* 
* *iacstart_install_application*

In Ansible Tower add the two new Job Templates as nodes to your Workflow, first the database installation and then the application installation:

* Open *Templates->iacstart->WORKFLOW VISUALIZER*
* Add a node with the Job Template for the database
* Add a node with the Job Template for the application
* click *SAVE*

=== Run the complete Workflow

It's time to test the complete workflow.

* Start the workflow again, you have done this a couple of times already.
* Wait until it has finished (the last step becomes green)

TIP: The last step doing the application installation takes some time.

Now your webshop is deployed!

== Access your Webshop

To access the shop you need the public IP address:

* Log-in to the AWS Console and open the EC2 Dashboard. 
* Select the webserver instance ("iacstart_web") and lookup the public IP Address of the instance.
* Copy the IP address, open a new browser tab, paste and open it.

*Now you are open for business!*