:icons: font

= IaCStart - Let's move to good old europe

Due to a new regulation requirement it is no longer allowed to run the shop in the US. Therefore, you need to *delete the resources in the US* and to *deploy the shop into AWS region Europe (Frankfurt), shortname eu-central-1*. Because your complete application deployment is automated, this should be straight forward. A couple of things have to be taken care of, though: 

* First and foremost you have to point the workflow to the new region.
* The AMI IDs are region-specific in AWS, so you have to change the AMI ID, too.

So here are your tasks:

* In the *EXTRA VARIABLES* of your workflow *iacstart* change
** *region* to *eu-central-1*
** *aws_zone* to *eu-central-1a*
** Change *ami_id* to *ami-00f69856ea899baec*

TIP: *aws_zone* is one of the availability zones AWS provides in every region.

And one last thing:

* The dynamic inventory that was created for you points to the wrong region, too.  
* To change it open *Inventories->iacstart*, click the *SOURCES* button and edit the *iacstartaws* source.
* Find the *REGIONS* field, delete the old region and choose the correct new region from the drop-down
* *SAVE*

When you are done with these steps just run the workflow again. 

WARNING: Wait until the last step becomes green again.

== Access your Webshop

To access the shop:

* Log-in to the AWS Console and open the EC2 Dashboard (Services->EC2). 
* Make sure you are in region *Europe (Frankfurt) eu-central-1* (upper right side in the AWS console)
* Select the webserver instance *iacstart_web* and lookup the public IP Address of the instance.
* Copy the IP address, open a new browser tab, paste and open it.

*Now you are open for business in Europe!*