

:icons: font
:git: https://github.com/iacgame/nodejs_sample.git 

= IaCStart - Let's deploy your first app on AWS

Before we start with our Infrastructure-as-Code game, you will provision a small application manually. 

== Let's get started

Without further ado let's simply get started, you'll get more instructions on your way.

TIP: Remember to have fun!


== Description of the target environment

You will need to build virtual servers. 
Here are the specifications of the servers:

=== Web server:

* Instance Size: t2.micro
* Disk Size: 10GB
* AMI Image: Red Hat Enterprise Linux 8 (HVM), SSD Volume Type
* Network Access: SSH, HTTP, and HTTPS from any source
* Tag: Managed:Manual

=== Database server:

* Instance Size: t2.micro
* Disk Size: 10GB
* AMI Image: Red Hat Enterprise Linux 8 (HVM), SSD Volume Type
* Network Access: SSH from any source, mongodb (27017/tcp) from web servers
* Tag: Managed:Manual


== Cloud Environment on AWS 

Everything you'll do during this game is about deploying cloud-based infrastructures. We'll use Amazon Web Services which can be accessed using APIs or with a web console. 

=== Access the Amazon Web Services Console and create your user to work with

* Open the AWS console https://console.aws.amazon.com/
* Log-in with the provided Credentials
* Creates new user to work with
** Open the IAM-Console (Service Menu on the top)
** Select on the left site the User menu
** Provide a username of your choice
** Check the "Programmatic access" and "AWS Management Console access" checkboxes
** Provide a custom password and deselect the "User must create a new password at next sign-in" checkbox
** Click "Next: Permissions"
** Select "Attach existing policies directly" and select "AdministratorAccess" in the policy list
** Click "Next: Tags" and leave the tags unchanged and click "Next: Review" to review the user settings
** If everything looks right, click the "Create User" Button
* After the user is successfully created, a result page will be shown, where you can download the access key for later use. 
To do so, click on the "Download .csv" button and store the file on your machine.
* Logout from the AWS console and log in again with the created user. 
* Verify that you are connected to the *USA Ost (Northern-Virginia) us-east-1* Region in the top right corner. If not, change to that region.

=== Create a VPC

TIP: In your account is a default VPC in each region. For your deployment, we will use a new dedicated VPC.

* The VPC is your virtual data center, where all the resources will be located. 
* The VPC boundary is the network. 
* Please use the following CIDR for your VPC 10.4.0.0/20

=== Create a Subnet within the VPC

Within the VPC, you need to create Subnets to connect your systems later on. 

* Select Subnets in the VPC Console and create one subnet in the new VPC with the CIDR 10.4.0.0/24
* After you have created the subnet, change the "auto-assign IP settings" to enable the assignment of public IP addresses. 

=== Internet Gateway and routing

* To enable access from the internet to the systems in this subnet you also need to create an internet gateway that needs to be connected to the new VPC.
* After you have created the Gateway to the internet, you also need to configure the default route (CIDR 0.0.0.0/0) in the routing table of the subnet to use the gateway. 

=== Create the ssh key pair for access to the Linux servers

* To log-in into newly provisioned servers, you need to provide a public ssh-key during the deployment where you have the private key.
* This key pair can be created in the AWS console in the EC2 dashboard where you can select "key pairs" and then "Create key pair".
* Provide a name, so that you can identify the key during the later use.
* Select pem as file format as this format is important for the later use in the game
* When you click on "create key pair" the private key file will be downloaded

WARNING: This private key file will always be needed to access a server on AWS and can't be download later. So store the file in a secure place.

=== Create the EC2 instances for Web and DB

* Open the EC2 console and launch the two server instances as described above.

=== Configure the database server

* Connect to the server via ssh

** For macOS
*** Open the terminal
*** Change the permission of the downloaded pem file to 400
*** Connect to the public IP of the server with the user ec2-user (ssh -i "path to your pem file" ec2-user@"Public IP of the server")

** For Windows 
*** Use putty to connect to the server. You need to transform the pem file in a putty format. 
*** Details can be found here: 
https://docs.aws.amazon.com/de_de/AWSEC2/latest/UserGuide/putty.html 


* Install MongoDB

Add the MongoDB repository to the system. To do so, please create a new file */etc/yum.repos.d/mongodb-org-4.2.repo* and add the following content the file.

----
[mongodb-org-4.2]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc
----

----
sudo yum install -y mongodb-org
----

* Configure MongoDB to bind to any IP

----
sudo vi /etc/mongod.conf
----

Change bindIP to *0.0.0.0*

* Start MongoDB

----
sudo systemctl start mongod
----

=== Configure the webserver

* Connect to the web server via ssh

To run the web application some packages and configurations are needed. 

* Install git

----
sudo yum install git
----

* Clone repo

[subs="attributes"]
----
cd /opt
sudo git clone {git}
cd nodejs_sample
----

* Install nodejs

----
sudo yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
sudo yum install -y nodejs
----

* Install npm packages

----
sudo npm install express morgan object-assign ejs mongodb
----

* Configure Application

Open the file */opt/nodejs_sample/server.js* file. 
Change the database server IP address to the private IP address of your database server in the line "mongoHost".

* Start the app

Test that the app is running from the command line *sudo npm start*
Open the public URL of the webserver with your local browser to check the web site

* BONUS

Ensure that the webserver application is running after with as daemon with an enabled service. 

== Review what you have done so far.

* You have log-in into the AWS console and created a user to work with. 
* You have created the *access key* to access the AWS API and an *ssh key pair* to login into the servers on AWS.
* You have created your first VPC, Subnet, and virtual servers on AWS.
* You've installed and configured the web service and database on the servers.

== Clean up AWS

In the next sprints of the game, you will deploy the resources with Ansible. Therefore please clean up your AWS account.

* Open the EC2 console and select both running instances and set the *Instance state* to *Terminate* and wait until both instances are terminated.
* Open the VPC console and select your VPC and delete the VPC

WARNING: Do not delete the key pair. This will be needed in the next sprints. 










